# Generated by Django 5.1.1 on 2024-10-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course_status',
            field=models.CharField(choices=[('Avaiable', 'Avaiable'), ('Registered', 'Registered'), ('Full', 'Full')], default='Avaiable', max_length=10),
        ),
    ]
