# Generated by Django 5.1.1 on 2024-10-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0002_alter_subject_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('enrolled_subjects', models.ManyToManyField(blank=True, related_name='students', to='app_courses.subject')),
            ],
        ),
    ]
